server {
    listen 80;
    server_name www.hemnsystem.com.br hemnsystem.com.br dev.hemnsystem.com.br 129.121.45.136;

    if ($host = dev.hemnsystem.com.br) {
        return 301 https://$host$request_uri;
    }
    if ($host = www.hemnsystem.com.br) {
        return 301 https://$host$request_uri;
    } 
    if ($host = hemnsystem.com.br) {
        return 301 https://$host$request_uri;
    }
    
    location / {
        return 301 https://hemnsystem.com.br$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name dev.hemnsystem.com.br;
    client_max_body_size 500M;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    ssl_certificate /etc/letsencrypt/live/hemnsystem.com.br/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/hemnsystem.com.br/privkey.pem; 
    # Nota: Certificado SSL para o subdomínio será gerado após o deploy
}

server {
    listen 443 ssl default_server;
    server_name www.hemnsystem.com.br hemnsystem.com.br;
    client_max_body_size 500M;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    ssl_certificate /etc/letsencrypt/live/hemnsystem.com.br/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/hemnsystem.com.br/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
}
